# Generated by Django 5.2.1 on 2025-05-17 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=50, unique=True)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('type_utilisateur', models.CharField(choices=[('admin', 'Admin'), ('enseignant', 'Enseignant')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ElementModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_element', models.CharField(max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4)),
                ('volume_horaire', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='attendance.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('annee_academique', models.CharField(max_length=20)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='attendance.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=50)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='attendance.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_apogee', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('annee', models.IntegerField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='attendance.filiere')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='attendance.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='attendance.elementmodule')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='attendance.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=20)),
                ('nom_module', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4)),
                ('semestre', models.IntegerField()),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='attendance.filiere')),
            ],
        ),
        migrations.AddField(
            model_name='elementmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='attendance.module'),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_marquage', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('non_verifie', 'Non Vérifié')], max_length=15)),
                ('justifiee', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='attendance.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('type_notification', models.CharField(choices=[('absence', 'Absence'), ('rappel', 'Rappel')], max_length=10)),
                ('statut_envoi', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec'), ('en_attente', 'En attente')], max_length=10)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.etudiant')),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.presence')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_seance', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=2)),
                ('salle', models.CharField(max_length=50)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='attendance.elementmodule')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='attendance.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='RapportPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('envoye', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='attendance.elementmodule')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='attendance.enseignant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='attendance.seance')),
            ],
        ),
        migrations.AddField(
            model_name='presence',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='attendance.seance'),
        ),
        migrations.CreateModel(
            name='SessionQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_qr', models.CharField(max_length=255)),
                ('url_session', models.CharField(max_length=255)),
                ('timestamp_creation', models.DateTimeField(auto_now_add=True)),
                ('timestamp_expiration', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_qr', to='attendance.enseignant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_qr', to='attendance.seance')),
            ],
        ),
        migrations.AddField(
            model_name='presence',
            name='session_qr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to='attendance.sessionqr'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to='attendance.utilisateur'),
        ),
    ]
