# Generated by Django 5.2.1 on 2025-05-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='motif_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
